# database admins that are inserted on startup
database:
  admins:
    - a.lohmeijer@hotmail.com
user:
  roles:
    - admin
    - partner
    - coach
    - community_owner
attendance:
  options:
    - present 
    - absent
    - cancelled
