# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
files: ^(backend)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-docstring-first
        name: "✅ Check docstring"
      - id: trailing-whitespace
        name: "✅ Check trailing whitespace"
      - id: end-of-file-fixer
        name: "✅ Check end of file"
      - id: check-ast
        name: "✅ Check AST"
      - id: debug-statements
        name: "✅ Check debug statements"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
    hooks:
      - id: ruff
        name: "🧹 Lint code with Ruff"
        args: 
          - --line-length
          - "115"
          - --fix
        files: backend
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        name: "⚫ Format code with Black"
        args:
          - --safe
          - --quiet
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.0.0
    hooks:
      - id: pyupgrade
        name: "🆕 Check for code that can use new Python features"
        args: [--py311-plus]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.2
    hooks:
      - id: bandit
        name: "🔒 Check for security issues with Bandit"
        args:
          [
            --skip,
            "B101,B110,B311,B103,B108,B113",
            --exclude,
            backend/app/.venv,
            --recursive,
            backend
          ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        name: "🆎 Static type checking backend using mypy"
        pass_filenames: true
        entry: bash -c 'poetry -C backend run mypy backend/app'

