version: "3.1"

volumes:
  pgdata:

services:
  db: 
    ports:
      - 5432:5432
    image: postgres
    #restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DATABASE: ${POSTGRES_DATABASE:-digitallions}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_HOST: ${POSTGRES_HOST:-localhost}
      PGDATA: /var/lib/postgresql/data/digitallions
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
  backend:
    image: "digitallionsbackend:latest"
    build:
      context: ./backend
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DATABASE: ${POSTGRES_DATABASE:-digitallions}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_HOST: ${POSTGRES_HOST:-localhost}
    #volumes:
      #- ./app:/app
    ports:
      - 8000:8000

  frontend: 
    image: "digitallionsfrontend:latest"
    build: 
      context: ./frontend
    environment:
      API_URL: ${API_URL:-"https://localhost:8000/api/v1"}
    ports:
      - 8501:8501
