[tool.poetry]
name = "digital-lion"
version = "0.1.0"
description = ""
authors = ["Anne Lohmeijer <a.lohmeijer@hotmail.com>"]
readme = "README.md"
packages = [
    { include = "app"}
]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.109.2"
uvicorn = {extras = ["standard"], version = "^0.29.0"}
ruff = "^0.3.4"
isort = "^5.13.2"
psycopg2-binary = "2.9.5"
sqlmodel = "^0.0.18"
pydantic = {extras = ["email"], version = "^2.7.1"}
bcrypt = "^4.1.3"
alembic = "^1.13.1"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.4"
pytest-asyncio = "^0.23.3"
pytest-mock = "^3.11.1"
pytest-env= "^1.1.3"

[tool.poetry.scripts]
start = "python run app.main:start"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
