"""Update roles table

Revision ID: ecd236638299
Revises: 1a7a5d2855b8
Create Date: 2024-11-14 20:37:51.794807

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "ecd236638299"
down_revision: Union[str, None] = "1a7a5d2855b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "roles",
        sa.Column("level", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "roles", sa.Column("resource_id", sa.Integer(), nullable=False)
    )
    op.drop_column("roles", "entity_type")
    op.drop_column("roles", "entity_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "roles",
        sa.Column(
            "entity_id", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "roles",
        sa.Column(
            "entity_type", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("roles", "resource_id")
    op.drop_column("roles", "level")
    # ### end Alembic commands ###
