"""Update Role table

Revision ID: 1a7a5d2855b8
Revises: a14383ea407f
Create Date: 2024-11-14 20:29:47.563160

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "1a7a5d2855b8"
down_revision: Union[str, None] = "a14383ea407f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "roles",
        sa.Column(
            "entity_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
    )
    op.add_column(
        "roles",
        sa.Column(
            "entity_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
    )
    op.drop_column("roles", "scope")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "roles",
        sa.Column("scope", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("roles", "entity_id")
    op.drop_column("roles", "entity_type")
    # ### end Alembic commands ###
