"""Allow null values for role scope

Revision ID: a14383ea407f
Revises: c90551dc95a0
Create Date: 2024-11-14 08:45:17.923868

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "a14383ea407f"
down_revision: Union[str, None] = "c90551dc95a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "roles", "scope", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "roles", "scope", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
