"""Add unique constraint column

Revision ID: f012da4cc267
Revises: dae82ed2dabe
Create Date: 2025-01-15 17:05:59.021934

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "f012da4cc267"
down_revision: Union[str, None] = "dae82ed2dabe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "communities", "name", existing_type=sa.VARCHAR(), nullable=True
    )
    op.create_unique_constraint(None, "communities", ["name"])
    op.alter_column(
        "implementing_partners",
        "name",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.create_unique_constraint(None, "implementing_partners", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "implementing_partners", type_="unique")
    op.alter_column(
        "implementing_partners",
        "name",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.drop_constraint(None, "communities", type_="unique")
    op.alter_column(
        "communities", "name", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
