"""Change role type

Revision ID: e2111f447be3
Revises: b33b6d4dd027
Create Date: 2025-01-08 21:10:39.613365

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "e2111f447be3"
down_revision: Union[str, None] = "b33b6d4dd027"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "roles", sa.Column("resource_path", sa.Integer(), nullable=False)
    )
    op.drop_column("roles", "resource_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "roles",
        sa.Column(
            "resource_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("roles", "resource_path")
    # ### end Alembic commands ###
