"""Add RESTRICT

Revision ID: e1209222c8c1
Revises: f012da4cc267
Create Date: 2025-01-15 17:08:24.244155

"""

from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "e1209222c8c1"
down_revision: str | None = "f012da4cc267"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "communities_implementing_partner_id_fkey",
        "communities",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "communities",
        "implementing_partners",
        ["implementing_partner_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "communities", type_="foreignkey")
    op.create_foreign_key(
        "communities_implementing_partner_id_fkey",
        "communities",
        "implementing_partners",
        ["implementing_partner_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
