name: Deploy Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - backend/**

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set versions
        working-directory: backend
        run: |
          PYTHON_VERSION=$(cat .python-version)
          echo "PYTHON_VERSION=$PYTHON_VERSION" >> $GITHUB_ENV
          POETRY_VERSION=$(cat .poetry-version)
          echo "POETRY_VERSION=$POETRY_VERSION" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Poetry
        run: |
          pip install poetry==${{ env.POETRY_VERSION }}
      - name: Install dependencies
        working-directory: backend
        run: |
          poetry install --no-interaction --no-root
      - name: Pytest
        working-directory: backend
        run: |
          poetry run python -m pytest tests -vvv --cov=app 

  deploy_stg:
    name: Deploy Backend to Railway
    environment: staging
    needs: [test] 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy Backend
        run: railway up --service backend
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy Frontend
        run: railway up --service frontend
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}



