"""Custom exceptions for the app."""


class BadRequestError(Exception): ...


class ChildAlreadyExistsError(Exception): ...


class ChildHasAttendanceError(Exception): ...


class ChildNotFoundError(Exception): ...


class ChildNotInTeam(Exception): ...


class CommunityAlreadyExistsError(Exception): ...


class CommunityHasTeamsError(Exception): ...


class CommunityNotFoundError(Exception): ...


class ForbiddenError(Exception): ...


class ItemAlreadyExistsError(Exception): ...


class ItemNotFoundError(Exception): ...


class ResourceNotFoundError(Exception): ...


class RoleAlreadyExistsError(Exception): ...


class RoleNotFoundError(Exception): ...


class TeamHasChildrenError(Exception): ...


class TeamNotFoundError(Exception): ...


class UserEmailExistsError(Exception): ...


class UserNotFoundError(Exception): ...


class UserUnauthorizedError(Exception): ...


class WorkshopExistsError(Exception): ...


class WorkshopIncompleteAttendance(Exception): ...


class WorkshopNotFoundError(Exception): ...


class WorkshopNumberInvalidError(Exception): ...
