"""Custom exceptions for the app."""


class BadRequestError(Exception): ...


class ChildAlreadyExistsError(Exception): ...


class ChildHasAttendanceError(Exception): ...


class ChildNotFoundError(Exception): ...


class ChildNotInTeam(Exception): ...


class CommunityAlreadyExistsError(Exception): ...


class CommunityHasTeamsError(Exception): ...


class CommunityNotFoundError(Exception): ...


class ForbiddenException(Exception): ...


class ItemAlreadyExistsException(Exception): ...


class ItemNotFoundException(Exception): ...


class TeamHasChildrenException(Exception): ...


class TeamNotFoundException(Exception): ...


class UserEmailExistsError(Exception): ...


class UserNotFoundException(Exception): ...


class UserNotFoundError(Exception): ...


class UserUnauthorizedException(Exception): ...


class WorkshopExistsException(Exception): ...


class WorkshopIncompleteAttendance(Exception): ...


class WorkshopNotFoundException(Exception): ...


class WorkshopNumberInvalidException(Exception): ...
